### ISSUE TITLE
The stride of layer4

### ISSUE THREAD

**Issue by philokey** [ruotianluo/pytorch-resnet#2]
Hi,
I think the stride of layer4 in resnet should be 1, because in faster RCNN, the feature has been pooled into ` 7 * 7 `after layer 3.

**Comment by ruotianluo** [comment]
All the resnet module should remain the same, because we initialize using pertained model

**Comment by ruotianluo** [comment]
You are actually correct about the point you make about the faster RCNN, not sure if I need to change here. I will open an issue at faster-rcnn.
