### ISSUE TITLE
Why you multiply 255 and std in the fn of conv_kernel in CaffeParamProvider (in convert2.py?

### ISSUE THREAD

**Issue by simplysimleprob** [ruotianluo/pytorch-resnet#4]
Hi,

First of all, thank you for sharing your great work.
I am having hard time understanding why you multiply 255 and std in conv_kernel (line 30,  in convert2.py)
I thought you need to convert the weights BGR to RGB and divide by 255 and multiply by the std for accommodating the pytorch like input (RGB (0, 1) and normalized with the mean and std)

Please let me know what I am missing here.
Thank you.

**Comment by ruotianluo** [comment]
we want k_pth * (img_pth - mean_pth)/std = k_caffe * (img_caffe - mean_caffe)
because (img_pth - mean_pth) = (img_caffe - mean_caffe) / 255
thus,
k_pth = k_caffe * 255 * std
